### PR TITLE
Catalan translation

### PR DESCRIPTION
**Pull request by ccamara**
Addition of new Catalan translation files + fixing errors on existing ones.

### CODE REVIEW

**Comment by ccamara** [comment]
@kimhansen , After tryinng to help with Catalan and Spanish translations I have some noticed some things regarding files/folders that I do not understand and you may want to explain so I can proceed properly.
1. Folder FairphoneHome/res has some folders like layout-de layout-fr . These folders seem to be related to translation in few languages. However I have noticed that:
2. There are less layout-xx folders than languages: Does that mean that we can add new folders and some content on them?
3. Those folders contain a single file: fp_google_apps_installer_widget.xml. This file does not contain any localization string 
4. Some folders in FairphoneHome/res like values-fr contain two files: strings.xml and styles.xml whereas other such as values-es or values-en-rGR only contain one: strings.xml . Are styles.xml files needed or can be safely removed?

Regards

**Comment by javiercoll** [comment]
Hi @ccamara,

If you notice that there are 'missing' files in those cases, the app will
pick the default xml files, which can be found at 'values' or 'layout'
folders (let's say, the folders without language extension)

If you don't feel confident about it, I'll be pleased to colaborate with
your translations as we did with the deprecated repository.

Let me know! Cheers

**Comment by ccamara** [comment]
Hello @javiercoll

That was my first thought, but if you take further detail you'll see that `layout` folder's files do not have any string to be translated. Additionally it doesn't explain why does some languages have a `styles.xml` file inside which has exactly the same content each other. To make things worse, this content is also present in `layout/styles.xml` (Although it has much more content). All of these makes me think that:
1. `styles.xml` per language basis should be removed, since they have redundant information, in favour of more general file at `layout/styles.xml`.
2. `values-xx/styles.xml` should be removed, since they do not provide any per-language information and they are redundant.

If I am right in any of those assumptions I would be glad to do it in another branch/pull request, so I'll wait for @kimhansen's confirmation

And as per your suggestion, @javiercoll , I'd be more than glad to work again with you in translations. I've provided access to my forked repository so you can work there if you want to. You'll see that there are two branches for this purpose: `translation-catalan` and `translation-spanish`. My idea is to work on different branches for different languages so they can have different pull requests, making easier to review and possibly to collaborate (there may be some Spanish-speaking collaborators that don't know Catalan). This pull request, for example, was originally intended to centralize all Catalan translations, since it's pulling all changes in `translation-catalan` branch whereas https://github.com/Kwamecorp/Fairphone/pull/5 is intentended to fix some Spanish translations issues.

Cheers

**Comment by javiercoll** [comment]
Good morning,

The fastest way to check that is to remove the files and check it on the android emulator. If it doesn't explode, that's it. Althought, if you create a branch only for that and @kimhansen doesn't feel right about it, he just has to discard it.

Thanks for giving me access! I've been checking it and everything seems ok, so I won't touch anything. If you find anything I can help you with, please open an issue or write me.

Bye!

P.S: My knowledge on android development is quite limited - in fact, that's the first time I work in an android application. So maybe I'm wrong!

**Comment by ccamara** [comment]
Thanks for your contributions, @javiercoll ! It's been a nice surprise to find another catalan fairphone user/prosumer and it's a pleasure to team up with you in order to make Fairphone better!

**Pull request merged**
